networks:
  est-bridge:
    name: est_bridge

secrets:
  influx-token:
    file: ./secrets/influx_token

services:

  # ---------------------------------------------------------------------------------------------------------
  # DATABASE SERVICE - InfluxDB2
  # ---------------------------------------------------------------------------------------------------------

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ${INFLUX_ROOT}/influxdb2-data:/var/lib/influxdb2
      - ${INFLUX_ROOT}/influxdb2-config:/etc/influxdb2
      - ${INFLUX_ROOT}/environmental_sensor_telemetry_data.csv:/environmental_sensor_telemetry_data.csv
      - ${INFLUX_ROOT}/scripts:/docker-entrypoint-initdb.d
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influx-token
    networks:
      - est-bridge
    secrets:
      - influx-token

  # ---------------------------------------------------------------------------------------------------------
  # MESSAGE BROKER SERVICE - ECLIPSE MOSQUITTO
  # ---------------------------------------------------------------------------------------------------------

  mosquitto-broker:
    image: eclipse-mosquitto:2
    container_name: mosquitto-broker
    volumes:
      - ${MOSQUITTO_ROOT}/config:/mosquitto/config:ro
      - ${MOSQUITTO_ROOT}/data:/mosquitto/data
      - ${MOSQUITTO_ROOT}/log:/mosquitto/log
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # WebSockets
    stdin_open: true 
    tty: true
    networks:
      - est-bridge

  # ---------------------------------------------------------------------------------------------------------
  # MOCK SENSOR SERVICES - PYTHON
  # ---------------------------------------------------------------------------------------------------------

  first-sensor:
    image: environmental-sensor
    container_name: first-sensor
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_ORG=${ORG}
      - INFLUXDB_BUCKET=${BUCKET}
      - DEVICE_MAC_ADDR=${FIRST_SENSOR_MAC_ADDR}
      - MQTT_BROKER_HOST=${MOSQUITTO_HOST}
      - MQTT_BROKER_PORT=${MOSQUITTO_PORT}
    depends_on:
      - mosquitto-broker
      - influxdb
    networks:
      - est-bridge
    secrets:
      - influx-token

  second-sensor:
    image: environmental-sensor
    container_name: second-sensor
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_ORG=${ORG}
      - INFLUXDB_BUCKET=${BUCKET}
      - DEVICE_MAC_ADDR=${SECOND_SENSOR_MAC_ADDR}
      - MQTT_BROKER_HOST=${MOSQUITTO_HOST}
      - MQTT_BROKER_PORT=${MOSQUITTO_PORT}
    depends_on:
      - mosquitto-broker
      - influxdb
    networks:
      - est-bridge
    secrets:
      - influx-token

  third-sensor:
    image: environmental-sensor
    container_name: third-sensor
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_ORG=${ORG}
      - INFLUXDB_BUCKET=${BUCKET}
      - DEVICE_MAC_ADDR=${THIRD_SENSOR_MAC_ADDR}
      - MQTT_BROKER_HOST=${MOSQUITTO_HOST}
      - MQTT_BROKER_PORT=${MOSQUITTO_PORT}
    depends_on:
      - mosquitto-broker
      - influxdb
    networks:
      - est-bridge
    secrets:
      - influx-token

  # ---------------------------------------------------------------------------------------------------------
  # ANALYTICS SERVICE - NODE + TS
  # ---------------------------------------------------------------------------------------------------------

  analytics-engine:
    image: environmental-telemetry-analytics
    container_name: analytics-engine
    environment:
      - MQTT_BROKER_HOST=${MOSQUITTO_HOST}
      - MQTT_BROKER_PORT=${MOSQUITTO_PORT}
      - SAMPLE_WINDOW_SIZE=${SAMPLE_WINDOW_SIZE}
      - DEVIATION_PERCENT_THRESHOLD=${DEVIATION_PERCENT_THRESHOLD}
    depends_on:
      - first-sensor
      - second-sensor
      - third-sensor
    networks:
      - est-bridge
  
  # ---------------------------------------------------------------------------------------------------------
  # CLICKHOUSE - HTAP DB + WEB UI
  # ---------------------------------------------------------------------------------------------------------

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "9000:9000" # clickhouse protocol
      - "8123:8123" # http
    volumes:
      - ${CLICKHOUSE_ROOT}/:/docker-entrypoint-initdb.d/:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - est-bridge

  # curl -X POST 'http://localhost:8123/' --data-binary 'SELECT * FROM environmental_sensor_telemetry.sensor_data FORMAT JSON;'

  # ---------------------------------------------------------------------------------------------------------
  # EVENT INFO SERVICE - C# (.NET)
  # ---------------------------------------------------------------------------------------------------------

  event-info:
    image: environmental-telemetry-event-info
    container_name: event-info
    environment:
      - MQTT_BROKER_HOST=${MOSQUITTO_HOST}
      - MQTT_BROKER_PORT=${MOSQUITTO_PORT}
      - MQTT_EVENTS_TOPIC=${MQTT_EVENTS_TOPIC}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
    depends_on:
      - analytics-engine
      - clickhouse
    networks:
      - est-bridge
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
